### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by gilanvirad084** [imkeithyang/Neural-McKean-Vlasov-Processes#1]
Hello, thanks for the great work! I was trying to run your code but it seems that there are some missing documents like: nets_fk and ot
 File "/content/Neural-McKean-Vlasov-Processes/mean_train_fk.py", line 15, in <module>
    from mf_fk import FKModule
  File "/content/Neural-McKean-Vlasov-Processes/mf_fk.py", line 6, in <module>
    from nets_fk import SMLP
ModuleNotFoundError: No module named 'nets_fk'

I would highly appreciate it if you could guide me through the issue.
Thanks

**Comment by imkeithyang** [comment]
Hello, we have fixed the nets_fk issue nets_fk.py is not a needed file to run the code. Also, ot is a package called POT: [https://pythonot.github.io/](https://pythonot.github.io/). We have also added a requirements.txt.

**Comment by gilanvirad084** [comment]
Thanks
